---
- name: Case 03330413 replication
  hosts: localhost

  tasks:
  - name: Create a credential type
    ansible.controller.credential_type:
      controller_host: "{{ controller_host }}"
      controller_password: "{{ password }}"
      controller_username: "{{ username }}"
      name: Case 03330413 creds
      description: Testing credentials from case 03330413
      kind: cloud
      inputs: "{{ lookup('file', 'creds_input.json') }}"
      injectors: "{{ lookup('file', 'creds_injector.json') }}"
      state: present
      validate_certs: false

  - name: Create a credential
    ansible.controller.credential:
      controller_host: "{{ controller_host }}"
      controller_password: "{{ password }}"
      controller_username: "{{ username }}"
      name: Case 03330413 creds - testing
      credential_type: Case 03330413 creds
      inputs:
        username: admin
